version: '3.4'
services:
  kerberos1:
    image: "kerberos/kerberos"
    ports:
     - ${KER1}
     - "8889:8889"
    volumes:
     - ${MEDIA_FOLDER}/kerberos1/capture:/etc/opt/kerberosio/capture
     - ${USERDIR}/docker/shared:/shared
     - ${USERDIR}/docker/kerberos1/config:/etc/opt/kerberosio/config
  kerberos2:
    image: "kerberos/kerberos"
    ports:
     - ${KER2}
     - "8890:8890"
    volumes:
     - ${MEDIA_FOLDER}/kerberos2/capture:/etc/opt/kerberosio/capture
     - ${USERDIR}/docker/shared:/shared
     - ${USERDIR}/docker/kerberos2/config:/etc/opt/kerberosio/config
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    ports:
      - ${PORTA}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/portainer/data:/data
      - ${USERDIR}/docker/shared:/shared
    environment:
      - TZ=${TZ}
  homeassistant:
    container_name: homeassistant
    restart: always
    image: homeassistant/armhf-homeassistant
    volumes:
      - ${USERDIR}/docker/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/shared:/shared
    ports:
      - ${HMAS}
    privileged: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
